# 1. Feature Selection (For Data Engineer)
features:
  numerical_cols:
    - area
    - bathroom
    - balcony
    - room_floor
    - total_floor
    - main_road_view
    - amenity_view
  categorical_cols:
    - location
    - transaction
    - furnishing
    - facing
    - ownership

# 2. Model Parameters (For Model Engineer)
model_params:
  algorithm: "RandomForestRegressor"
  n_estimators: 100
  max_depth: 5
  random_state: 42

# 3. Experiment Settings (Pipeline Branching)
experiment:
  target_transform: "log" # Toggle: "raw" (giữ nguyên) hoặc "log" (dùng np.log1p)
  target_col: "amount" # Tên cột mục tiêu (giá nhà)
  log_features: # Danh sách các cột đầu vào cần lấy log
    - "area"

  top_k_features: 20 # Số lượng cột liên quan nhất được giữ lại (Gatekeeper)
