# 1. Feature Selection (For Data Engineer)
features:
  numerical_cols:
    - area
    - bathroom
    - balcony
    - room_floor
    - total_floor
    - main_road_view
    - amenity_view
  categorical_cols:
    - location
    - transaction
    - furnishing
    - facing
    - ownership

# 2. Model Parameters (For Model Engineer)
model_params:
  algorithm: "RandomForestRegressor"
  n_estimators: 100
  max_depth: 5
  random_state: 42